#cloud-config
write_files:
  - path: "/index.html"
    permissions: "0644"
    owner: "root"
    content: "hello world"
  - path: "/etc/systemd/system/lifecycled.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Autoscale Lifecycle Daemon
      Requires=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      Restart=on-failure
      RestartSec=30s
      TimeoutStopSec=5m

      Environment="AWS_REGION=${region}"
      ExecStart=/usr/local/bin/lifecycled --sns-topic=${lifecycle_topic} --cloudwatch-group=${log_group_name} --handler=/usr/local/scripts/lifecycle-handler.sh --json --debug

      [Install]
      WantedBy=multi-user.target
  - path: "/usr/local/scripts/lifecycle-handler.sh"
    permissions: "0744"
    owner: "root"
    content: |
      #! /usr/bin/bash

      set -euo pipefail

      echo "hello from the handler"
      sleep 120
      echo "goodbye from the handler"
runcmd:
  - |
    aws s3 cp s3://${artifact_bucket}/${artifact_key} /usr/local/bin/lifecycled
    chmod +x /usr/local/bin/lifecycled
    chown root:root /usr/local/bin/lifecycled
    echo "lifecycled ${artifact_etag} installed"
  - |
    systemctl enable lifecycled.service --now
  - |
    wget https://www.busybox.net/downloads/binaries/1.28.1-defconfig-multiarch/busybox-x86_64
    chmod +x busybox-x86_64
    nohup ./busybox-x86_64 httpd -f -p 3000 &
