name:                s3-full-access-policy-tests
version:             0.1.0.0
github:              "fpco/terraform-aws-foundation"
license:             MIT
author:              "Mike McGirr"
maintainer:          "mike@fpcomplete.com"
copyright:           "2018 FP Complete"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/s3-full-access-policy-tests#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  s3-full-access-policy-tests-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - s3-full-access-policy-tests

tests:
  s3-full-access-policy-tests-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - s3-full-access-policy-tests
